### ISSUE TITLE
Period in ADR title causes misformatting

### ISSUE THREAD

**Issue by donald-richardson-dxd** [structurizr/documentation#1]
If my title is, for example, "Node.js for Runtime" I get "S for Runtime". Fixed when I remove ".".  Escaping the period makes no difference.

**Comment by simonbrowndotje** [comment]
This seems to work for me ... which version of the CLI/Lite are you using?

**Comment by donald-richardson-dxd** [comment]
The issue only happens if I don’t number the title:

# My title with a period. Has issues.

# 44. My title with a period but numbered does not.

I don’t have that info on me right now but I’ll take a look see.

From: Simon Brown ***@***.***>
Date: Sunday, May 22, 2022 at 6:58 AM
To: structurizr/documentation ***@***.***>
Cc: Donald Richardson ***@***.***>, Author ***@***.***>
Subject: Re: [structurizr/documentation] Period in ADR title causes misformatting (Issue #1)

This seems to work for me ... which version of the CLI/Lite are you using?

**Comment by simonbrowndotje** [comment]
The ADRs importer is designed to work in conjunction with the [adr-tools](https://github.com/npryce/adr-tools) tool that uses a numerical ID followed by a period character. If you'd like to use a different format for your ADRs, you might want to extend [AdrToolsDecisionImporter](https://github.com/structurizr/documentation/blob/main/src/main/java/com/structurizr/documentation/importer/AdrToolsDecisionImporter.java), and override the `extractTitle` method. You can then use your custom implementation via the [!adrs keyword](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#architecture-decision-records-adrs), which now provides a way to specify a fully qualified class name of your custom ADR importer.
